# Generated by Django 2.2.2 on 2019-07-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quaterback', models.TextField()),
                ('widereceiver', models.TextField()),
                ('tightend', models.TextField()),
                ('coach', models.TextField()),
                ('cornerback', models.TextField()),
            ],
        ),
    ]
